=== EyalSeagull/schemastore/src/schemas/json/truescript.json
{
    "$id": "https://json.schemastore.org/truescript.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "TrueScript for *.tscript files",
    "description": "The Ultimate Script Language for monday.com - Â© 2024 MakeITSimple",
    "additionalProperties": false,
    "type": "object",
    "definitions": {
        "TrueScriptVersion": {
            "description": "TrueScript version info. Format: \"major.minor.patch\"",
            "type": "string",
            "pattern": "^\\d+\\.\\d+\\.\\d+$"
        },
        "UUID4": {
            "description": "Unique ID (UUID4)",
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
        },
        "Environment": {
            "description": "TrueScript environment",
            "type": "string",
            "enum": [
                "production",
                "staging",
                "development"
            ]
        },
        "MondayId": {
            "description": "Any monday.com ID",
            "type": "integer",
            "exclusiveMinimum": 0
        },
        "Result": {
            "description": "The result of the execution of the TrueScript",
            "type": "string",
            "enum": [
                "success",
                "error"
            ]
        }
    },
    "properties": {
        "truescript_version": {
            "description": "The minimal version to run this TrueScript. Format: \"major.minor.patch\"",
            "$ref": "#/definitions/TrueScriptVersion"
        },
        "id": {
            "description": "Unique ID of the TrueScript (UUID4)",
            "$ref": "#/definitions/UUID4"
        },
        "name": {
            "description": "Short description of the TrueScript",
            "type": "string"
        },
        "description": {
            "description": "A more detailed description of the TrueScript",
            "type": "string"
        },
        "environment": {
            "description": "Intended environment to run the TrueScript",
            "$ref": "#/definitions/Environment"
        },
        "item_id": {
            "description": "The item's ID to execute the TrueScript upon",
            "$ref": "#/definitions/MondayId"
        },
        "params": {
            "description": "Parameters that will be passed to the TrueScript",
            "type": "object",
            "additionalProperties": true
        },
        "tags": {
            "description": "Free tags for any classification",
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "result": {
            "description": "The expected result when running this TrueScript",
            "type": "object",
            "properties": {
                "result": {
                    "description": "The result of the execution of the TrueScript.'",
                    "$ref": "#/definitions/Result"
                },
                "error": {
                    "description": "The error info (when 'result=error')",
                    "type": "object",
                    "properties": {
                        "additionalProperties": true
                    }
                }
            },
            "required": [
                "result"
            ]
        },
        "script": {
            "description": "The TrueScript itself",
            "type": "string"
        }
    },
    "required": [
        "truescript_version",
        "id",
        "name",
        "environment",
        "item_id",
        "script"
    ]
}

=== EyalSeagull/schemastore/src/test/truescript/truescript.json
{
    "id": "d901c6d8-3814-4f8d-9fef-72e9bebf4409",
    "truescript_version": "0.1.0",
    "name": "Variable Assignment",
    "description": "Testing variable assingment",
    "environment": "development",
    "item_id": 1,
    "tags": [
        "example",
        "noerror"
    ],
    "params": {
        "filter": "all*",
        "order_by": "date65",
        "order_desc": "desc"
    },
    "result": {
        "result": "error"
    },
    "script": "$var1 = 100;\r\n$var2=\"Teste\""
}
